version: '3.8'

services:
  mermaid-render-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TIME: ${BUILD_TIME:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}
        COMMIT_HASH: ${COMMIT_HASH:-$(git rev-parse --short HEAD)}
        VERSION: ${VERSION:-1.0.0}
    image: mermaid-render-gateway:latest
    container_name: mermaid-render-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CHROME_PATH=/usr/bin/chromium-browser
      - RENDER_TIMEOUT=30000
      - MAX_CONCURRENT_RENDERS=5
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN  # Required for Chrome sandboxing
    tmpfs:
      - /tmp:size=1G,noexec,nosuid,nodev

  # 可选：Redis缓存服务
  redis:
    image: redis:7-alpine
    container_name: mermaid-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # 可选：Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: mermaid-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mermaid-render-gateway
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: mermaid-network